version: '3.8'

services:
  # Digital Money House Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital-money-house-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Mount volume for development (optional)
      - ./src:/app/src:ro
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - dmh-network

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: dmh-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - dmh-network

  # Nginx reverse proxy (optional for production)
  nginx:
    image: nginx:alpine
    container_name: dmh-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - dmh-network

volumes:
  redis_data:
    driver: local

networks:
  dmh-network:
    driver: bridge